### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by tedstriker** [joshmarinacci/ElectronIDE#67]
Hi @joshmarinacci,

just wondering - did you abandon this project?

regards,
Ted

**Comment by joshmarinacci** [comment]
Hi Ted. Yes, I did.  It became increasingly difficult to do the serial port integration and no one was using the IDE anyway. Now that the Arduino team is putting more effort into improving the official IDE it felt like Electron wasn’t needed anymore.

-j

**Comment by tedstriker** [comment]
Thank you for your quick response. It's a pity it got abandoned. Electron was way more appealing than Arduino.cc's software ever will. Quite similar to codebender, but without the cloud. I liked the idea.
Anyways, good luck with your future projects.
